[tool.poetry]
name = "poche"
version = "0.1.0"
description = ""
authors = ["etienne-napoleone <etienne.napoleone@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8-black = "^0.1.1"
coverage = "^5.0"
mypy = "^0.761.0"
codecov = "^2.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
